/** Declaration file generated by dts-gen */
declare module 'ethereum-qr-code';

export = ethereum_qr_code;

declare class ethereum_qr_code {
    constructor();

    assignPluguinValues(...args: any[]): void;

    getJSON(): any;

    produceEncodedValue(config: any, options: any): any;

    readStringToJSON(valueString: any): any;

    toAddressString(config: any): any;

    toCanvas(config: any, options: any): any;

    toDataUrl(config: any, options: any): any;

}

